name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout SDK Codebase Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.SDK_Codebase_Repository_Branch }}
          repository: 'HamzaOban/testSDK'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
  
      - name: Publish SDK Version to GitHub
        run: |
          echo "======================================================================="
          echo " StepName:    Publishing new SDK version to GitHub                     "
          echo "======================================================================="
          git config user.email "hamzaoban3@gmail.com"
          git config user.name "HamzaOban"
          git remote set-url origin https://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@github.com/HamzaOban/TestRelease.git
          git checkout main
          git status
          echo "status log"
          git fetch origin
          git branch -a
          echo "branch log"
          git config pull.rebase true
          git pull origin main
          echo "pull log"
          echo "add log"
          echo "commit log"
          git push --set-upstream origin main
          echo "push logsa"

